/flush5/sho092/Robust_learning/MAML-Pytorch
Namespace(batch_size=1, batchsz=100000, crop_size=120, data_dist_same=False, epoch=60000, folder_name='', imgc=3, k=7, load='.', meta_lr=0.001, num_workers=1, pin_memory=True, print_every=5, root='/OSM/CBR/D61_RCV/students/sho092/', save_every=20, save_name='.', seed=1, shuffle=True, task_num=5, test_only=False, update_lr=0.01, update_step=5, update_step_test=10)
Traceback (most recent call last):
  File "sr_train.py", line 186, in <module>
    main()
  File "sr_train.py", line 40, in main
    ck = util.checkpoint(args)
  File "/flush5/sho092/Robust_learning/MAML-Pytorch/utility.py", line 78, in __init__
    _make_dir(self.dir)
  File "/flush5/sho092/Robust_learning/MAML-Pytorch/utility.py", line 76, in _make_dir
    if not os.path.exists(path): os.makedirs(path)
  File "/apps/python/3.6.1/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '../experiment/2020-05-05-18:48:00_.'
